immo_trakt:
  frequency: 1m #every 1 min
  include_existing_offers: false
telegram:
  token: botToken
  chat_id: #Can be left empty
immobilien_scout:
  search: https://www.immobilienscout24.de/Suche/de/berlin/berlin/wohnung-mit-balkon-mieten?price=-1000.0&pricetype=calculatedtotalrent&enteredFrom=result_list
  exclude_wbs: false #to exclude offers that contains word WBS in their title
  exclude_tausch: false #to exclude offers that contains word TAUSCH in their title
  exclude_senior: false #to exclude offers that contains word SENIOR in their title